services:
  mysql:
    image: mysql:8.4
    container_name: auction-app-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auction_db
      MYSQL_USER: auction_user
      MYSQL_PASSWORD: auction_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
